---
# ELK playbooks to pre-configure systems, and install/start individual components.
#
# Note: ELK services MUST be brought up in the order below.
- name: install and configure ELK stack
  hosts: all
  gather_facts: true

  vars:
    elk_cluster_name: elk-demo

  tasks:
    - ansible.builtin.include_role:
        name: pre

    - ansible.builtin.include_role:
        name: elasticsearch

    - name: validate that elasticsearch is up and available
      ansible.builtin.uri:
        url: http://{{ ansible_default_ipv4.address }}:9200
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 2

    - ansible.builtin.include_role:
        name: kibana

    - ansible.builtin.include_role:
        name: logstash

    - name: wait for service to begin listening
      ansible.builtin.wait_for:
        port: 5055
        delay: 30

  #  - ansible.builtin.include_role:
  #       name: filebeat

    - ansible.builtin.include_role:
          name: ssl

    - ansible.builtin.include_role:
          name: xpack

    - ansible.builtin.import_role:
        name: redhat_cop.controller_configuration.settings
      delegate_to: localhost
      vars:
        controller_hostname: "{{ controller_host | default(lookup('env','TOWER_HOSTNAME')) }}"
        controller_username: "{{ controller_user | default(lookup('env','TOWER_USERNAME')) }}"
        controller_password: "{{ controller_pass | default(lookup('env','TOWER_PASSWORD')) }}"
        controller_validate_certs: "{{ controller_ssl_validate | default('False') }}"
        controller_settings:
          - name: LOG_AGGREGATOR_HOST
            value: "http://{{ groups['elasticsearch'][0] }}"
          - name: LOG_AGGREGATOR_PORT
            value: 5055
          - name: LOG_AGGREGATOR_TYPE
            value: "logstash"
          - name: LOG_AGGREGATOR_USERNAME
            value: ""
          - name: LOG_AGGREGATOR_PASSWORD
            value: ""
          - name: LOG_AGGREGATOR_LOGGERS
            value: ["awx", "activity_stream", "job_events", "system_tracking"]
          - name: LOG_AGGREGATOR_INDIVIDUAL_FACTS
            value: false
          - name: LOG_AGGREGATOR_ENABLED
            value: true
          - name: LOG_AGGREGATOR_TOWER_UUID
            value: ""
          - name: LOG_AGGREGATOR_PROTOCOL
            value: "https"
          - name: LOG_AGGREGATOR_TCP_TIMEOUT
            value: 5
          - name: LOG_AGGREGATOR_VERIFY_CERT
            value: false
          - name: LOG_AGGREGATOR_LEVEL
            value: "INFO"
          - name: LOG_AGGREGATOR_MAX_DISK_USAGE_GB
            value: 1
          - name: LOG_AGGREGATOR_MAX_DISK_USAGE_PATH
            value: "/var/lib/awx"
          - name: LOG_AGGREGATOR_RSYSLOGD_DEBUG
            value: false
...
