---
galaxy_info:
  author: "Lumen"
  license: BSD
  min_ansible_version: 1.9
  description: "generate certs"
  #
  # Below are all platforms currently available. Just uncomment
  # the ones that apply to your role. If you don't see your
  # platform on this list, let us know and we'll get it added!
  #
  platforms:
  - name: EL
    versions:
    - 7
    - 8
  - name: GenericBSD
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  # Below are all categories currently available. Just as with
  # the platforms above, uncomment those that apply to your role.
  #
