- name: Copy Certificate Authority key file (if required)
  copy:
    content: "{{ ssl_certs_ca_privkey }}"
    dest: "{{ ssl_certs_ca_privkey_path }}"
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"
    force: "{{ ssl_certs_force_replace }}"
  when: ssl_certs_ca_privkey is defined

- name: Copy Certificate Authority certificate file (if required)
  copy:
    content: "{{ ssl_certs_ca_cert }}"
    dest: "{{ ssl_certs_ca_cert_path }}"
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"
    force: "{{ ssl_certs_force_replace }}"
  when: ssl_certs_ca_cert is defined

- name: Generate RSA key
  command: "openssl genrsa -out {{ ssl_certs_privkey_path }} {{ ssl_certs_key_size }}"
  args:
    creates: "{{ ssl_certs_privkey_path }}"

- name: RSA key file ownership
  file:
    path: "{{ ssl_certs_privkey_path }}"
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"

- name: Generate certificate config file
  template:
    src: sslcert.conf.j2
    dest: "{{ ssl_certs_conf_path }}"
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"

- name: Generate CSR
  command: "openssl req -config {{ ssl_certs_conf_path }} -new -sha256 -key {{ ssl_certs_privkey_path }} -out {{ ssl_certs_csr_path }}"
  args:
    creates: "{{ ssl_certs_csr_path }}"

- name: CSR file ownership
  file:
    path: "{{ ssl_certs_csr_path }}"
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"

- name: Generate self-signed SSL certificate w/ CA Cert
  command: "openssl x509 -req -in {{ ssl_certs_csr_path }} -CA {{ ssl_certs_ca_cert_path }} -CAkey {{ ssl_certs_ca_privkey_path }} -CAcreateserial -out {{ ssl_certs_cert_path }} -days 3650 -extensions req_ext -extfile {{ ssl_certs_conf_path }}"
  args:
    creates: "{{ ssl_certs_cert_path }}"
  when: ssl_certs_ca_cert is defined

- name: Generate self-signed SSL certificate without CA Cert
  command: "openssl req -config {{ ssl_certs_conf_path }} -nodes -x509 -sha256 -days {{ ssl_certs_days }} -in {{ ssl_certs_csr_path }} -key {{ ssl_certs_privkey_path }} -out {{ ssl_certs_cert_path }} -extensions v3_ca"
  args:
    creates: "{{ ssl_certs_cert_path }}"
  when: ssl_certs_ca_cert is not defined

- name: Self-signed SSL certificate file ownership
  file:
    path: "{{ ssl_certs_cert_path }}"
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"
  when: ssl_certs_generate_self_signed
